apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmi2
  template:
    metadata:
      labels:
        app: okmi2
    spec:
      containers:
      - image: okteto.dev/okmi2:latest
        name: okmi2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "db1374cc-01c3-4a48-8485-85c29db92cc3"
        - name: Vless_Path
          value: "/db1374cc-01c3-4a48-8485-85c29db92cc3-vless"
        - name: Vmess_UUID
          value: "db1374cc-01c3-4a48-8485-85c29db92cc3"
        - name: Vmess_Path
          value: "/db1374cc-01c3-4a48-8485-85c29db92cc3-vmess"
        - name: Trojan_UUID
          value: "db1374cc-01c3-4a48-8485-85c29db92cc3"
        - name: Trojan_Path
          value: "/db1374cc-01c3-4a48-8485-85c29db92cc3-trojan"
        - name: SS_UUID
          value: "db1374cc-01c3-4a48-8485-85c29db92cc3"
        - name: SS_Path
          value: "/db1374cc-01c3-4a48-8485-85c29db92cc3-ss"
        - name: Share_Path
          value: "/db1374cc-01c3-4a48-8485-85c29db92cc3-share"
